### ISSUE TITLE
template: IFC4x3_ADD2 should be with capital X

### ISSUE THREAD

**Issue by MennoMekes** [c4rlosdias/ids_converter#16]
In the template on the SUPPORT sheet IDS version 4x3 is written like this: IFC4x3_ADD2 but it should be IFC4X3_ADD2 with a capital X
Otherwise it doesn’t work.

**Comment by MennoMekes** [comment]
Hi Carlos,

Thanks a lot for fixing the convertor! 

This issue is still open. In the template the x should be Capitals.
If I change this the convertor does not work. I also need to change it to IFC4X3 without the _ADD2.
Then, the IDS is converted. However, checkers are not working because they accept only IFC4 or IFC4X3_ADD2.

**Comment by c4rlosdias** [comment]
fixed!

**Comment by MennoMekes** [comment]
Sorry to keep coming back to this but the Ifc version is still not working.
The convertor does not accept IFC4X3_ADD2. When I change it to IFC4X3 it converts. But then, the checkers don't work beceause they look for IFC4X3_ADD2.

This is the error message I get when running the convertor with the latest template:


ERRO : Review your spreadsheet, there's something wrong with your specification!

XMLSchemaValidationError: failed validating 'IFC4X3_ADD2' with XsdEnumerationFacets(['IFC2X3', 'IFC4', 'IFC4X3']): Reason: value must be one of ['IFC2X3', 'IFC4', 'IFC4X3'] Schema component: <xs:enumeration xmlns:xs="http://www.w3.org/2001/XMLSchema" value="IFC2X3" /> Instance type: <class 'xml.etree.ElementTree.Element'> Instance: <specification xmlns="http://standards.buildingsmart.org/IDS" name="IfcProject info" ifcVersion="IFC4X3_ADD2" description="controleert informatie van het project"> <applicability minOccurs="1" maxOccurs="unbounded"> <entity> <name> <simpleValue>IFCPROJECT</simpleValue> </name> </entity> </applicability> <requirements> <attribute cardinality="required"> <name> <simpleValue>Name</simpleValue> </name> <value> <simpleValue>Schuitenhuis</simpleValue> </value> </attribute> <property dataType="IFCLABEL" cardinality="required"> <propertySet> <simpleValue>Pset_ProjectCommon</simpleValue> ... ... </specification>
Traceback:
File "/mount/src/ids_converter/pages/1_💾_xlsx_to_IDS_xml.py", line 350, in <module>
    st.session_state.ids = my_ids.to_string()
                           ^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/ifctester/ids.py", line 135, in to_string
    return etree_tostring(get_schema().encode(self.asdict()), namespaces=ns)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/schemas.py", line 2239, in encode
    for result in self.iter_encode(obj, path, validation, *args, **kwargs):
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/schemas.py", line 2225, in iter_encode
    yield from xsd_element.iter_encode(obj, validation, **kwargs)
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/elements.py", line 1070, in iter_encode
    for result in xsd_type.content.iter_encode(element_data, validation, **kwargs):
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/groups.py", line 1198, in iter_encode
    for result in xsd_element.iter_encode(value, validation, **kwargs):
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/elements.py", line 1070, in iter_encode
    for result in xsd_type.content.iter_encode(element_data, validation, **kwargs):
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/groups.py", line 1198, in iter_encode
    for result in xsd_element.iter_encode(value, validation, **kwargs):
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/elements.py", line 1080, in iter_encode
    yield self.validation_error(validation, e, elem, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/xsdbase.py", line 249, in validation_error
    raise error
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/simple_types.py", line 1475, in iter_encode
    validator(obj)
File "/home/adminuser/venv/lib/python3.11/site-packages/xmlschema/validators/facets.py", line 633, in __call__
    raise XMLSchemaValidationError(self, value, reason)
ERRO : File not created!
